# -*- coding: utf-8 -*-
"""P2 Extra .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rfbuKXrK0J1AY1miF3MRZEZDLB4tKa4g

USN NO- CS23082
 Mrunal Samrutwar
 Extra Dataset Codes Based On practical 2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

from google.colab import files
files.upload()

import os
print(os.listdir())

data = pd.read_csv("insurance[1].csv")

data = pd.read_csv("insurance[1].csv")
print(data.head())

print(data.info())
print(data.describe())

print(data.isnull().sum())

data_encoded = pd.get_dummies(data, drop_first=True)
print(data_encoded.head())

X = data_encoded.drop("charges", axis=1)
y = data_encoded["charges"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("Mean Absolute Error (MAE):", mae)
print("R2 Score:", r2)

comparison = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})
print(comparison.head())

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})
print(coefficients)

print("Intercept:", model.intercept_)

residuals = y_test - y_pred

plt.scatter(y_pred, residuals)
plt.axhline(y=0)
plt.xlabel("Predicted Values")
plt.ylabel("Residuals")
plt.title("Residual Plot")
plt.show()

plt.hist(residuals)
plt.xlabel("Prediction Error")
plt.ylabel("Frequency")
plt.title("Error Distribution")
plt.show()

new_data = X.iloc[:1]
prediction = model.predict(new_data)

print("Predicted Insurance Charge:", prediction)