# -*- coding: utf-8 -*-
"""Practical 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9gxgLvpYSP21jzISVKt-UjWvZxQOHL1

Lab 3:  To implement Logistic Regression for binary or multiclass
classification problems and analyse the classification performance.
Mrunal Samrutwar (CS23082)
"""

import seaborn as sns
import pandas as pd
import numpy as np

df = sns.load_dataset('iris')
df.head()

df.describe()

df.info()

df.shape

df['species'].unique()

df.isnull().sum()

df=df[df['species']!='setosa']

df.shape

df['species'].unique()

df['species'] = df['species'].map({'versicolor': 0, 'virginica': 1})

X = df.iloc[:,:-1]
print(X)

y = df.iloc[:,-1]
print(y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7,test_size=0.3,random_state=42)

print(X_train.shape)

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()

# Hyper parameter tunning
from inspect import Parameter
from sklearn.model_selection import GridSearchCV
parameter={'penalty':['l1','l2','elasticnet'],'C':[1,2,3,4,5,6,10,20,30,40,50],'max_iter':[100,200,300,400]}

classifier_regressor = GridSearchCV(classifier, param_grid= parameter, scoring='accuracy',cv=5)

classifier_regressor.fit(X_train,y_train)

print(classifier_regressor.best_params_)

print(classifier_regressor.best_score_)

y_pred = classifier_regressor.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report

score = accuracy_score(y_pred, y_test)
print(score)

# For Precision,  Recall, F1 Score & Accuracy
print(classification_report(y_pred, y_test))

sns.pairplot(df, hue='species')

df.corr()