# -*- coding: utf-8 -*-
"""Practical 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tNtgSuyFsxIyDGVK4qAWRuqLP7z0LwgI

USN NO- CS23082
Mrunal Samrutwar
Aim: To implement Linear Regression for predicting continuous target
variables and evaluate the model performance using appropriate metrics.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

housing =fetch_california_housing()

df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['target'] = housing.target

print(df.head())

df.shape

df.describe()

df.info()

x= df.drop('target', axis=1)
y= df['target']

print(x)

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

x_train.shape

x_test.shape

y_train.shape

y_test.shape

model= LinearRegression()
model.fit(x_train, y_train)

y_pred =model.predict(x_test)

mae=mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("\nModel Evalution metrics")
print("------------------------------------------")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²): {r2}")

plt.scatter(x_test['MedInc'], y_test)
plt.scatter(x_test['MedInc'], y_pred)
plt.xlabel('MedInc income')
plt.ylabel('House Value')
plt.title('Linear Regression on California Hoising Dataset')
plt.show()

