# -*- coding: utf-8 -*-
"""Practical 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15BdXCAA6xKjypeLQcTm-6ZMBRkK9T4RG

Lab 1:To implement Linear Regression for predicting continous target variables and evaluate the

Mrunal Samrutwar (CS23082)

Pre-Lab: Understanding Google Colab and Python Libraries for Machine Learning,[NumPy, Pandas,Matplotlib,Seaborn,Sckit-learn]
"""

import numpy as np
#create arrays
a = np.array([1, 2, 3, 4])
b = np.zeros((2,3))
c = np.ones((2,3))
d = np.random.rand(2,3)
print(a)
print(b)
print(c)
print(d)

# array operations
print(a.shape)
print(a.mean)
print(a.std())
print(np.sum(a))
print(np.max(a))

# matrix opertions
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(np.dot(x, y))
print(np.transpose(x))

import pandas as pd
# create DataFrame
data = {
    'Age': [25, 30, 45],
    'Salary': [30000, 40000, 50000],
    'Department':['IT', 'HR', 'Finance']
}
df = pd.DataFrame(data)
print(df.describe())

# Handling missing values
df['salary'].fillna(df['salary'].mean(), inplace=True)

import pandas as pd
# encoding categorial data
data = {
    'Age': [25, 30, 45],
    'Salary': [30000, 40000, 50000],
    'Department':['IT', 'HR', 'Finance']
}
df_encoded = pd.get_dummies(df, drop_first=True)
print(df_encoded)

df_encoded = pd.get_dummies(df, drop_first=True)
print(df_encoded)

import matplotlib.pyplot as plt
x = [1, 2, 3, 4]
y = [2, 4, 6, 8]
plt.plot(x, y)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title('Line Plot')
plt.show()

# bar plot
plt.bar(x, y)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title('Bar Plot')
plt.show()

# scatter plot
plt.scatter(x, y)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title('Scatter Plot')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
# load sample dataset
df = sns.load_dataset('iris')
# create pair plot
sns.pairplot(df, hue='species')
plt.show()

# Box plot
sns.boxplot(x='species', y='petal_length', data=df)
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler